# Generated by Django 3.1.3 on 2020-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that mobile number already exists.'}, max_length=10, unique=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=60, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Last name'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='auth_user',
        ),
    ]
