# Generated by Django 3.1.4 on 2020-12-04 16:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201130_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('available_products', django.db.models.manager.Manager()),
            ],
        ),
    ]
